blog/urls.py
from django.urls import path
from . import views
from .models import Post
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    AuthorDetailView,
    CategoryListView,
    CommentCreateView,
    PostFormSetview,
    EditCategoryPosts,
)
from users.views import LoginUserView

app_name = "blog"

urlpatterns = [
    path("", PostListView.as_view(), name="post_list"),
    path("post/new/", PostCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("comment/<int:pk>/", CommentCreateView.as_view(), name="comment_new"),
    path(
        "comment/<int:pk>/parent/<int:parent>/",
        CommentCreateView.as_view(),
        name="comment_new_child",
    ),
    path(
        "post/category/<str:category>/",
        CategoryListView.as_view(),
        name="category_detail",
    ),
    path("post/<int:pk>/edit/", PostUpdateView.as_view(), name="post_edit"),
    path("author/<int:pk>/", AuthorDetailView.as_view(), name="author_detail"),
    # Form sets
    path("post/formset/", PostFormSetview.as_view(), name="post-formset"),
    path(
        "category/formset/<int:pk>/",
        EditCategoryPosts.as_view(),
        name="category-formset",
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
]

users/urls.py
from django.urls import path

from .views import (
    LoginUserView,
    LogoutUser,
    SignUpUser,
    PasswordReset,
    PasswordResetDone,
)
from django.contrib.auth.views import (
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy
from blog.urls import PostListView

app_name = "users"

urlpatterns = [
    path("accounts/login/", LoginUserView.as_view(), name="login"),
    path("accounts/logout", LogoutUser.as_view(), name="logout"),
    path("accounts/signup/", SignUpUser.as_view(), name="signup"),
    path("accounts/password_reset/", PasswordReset.as_view(), name="password_reset"),
    path(
        "accounts/password_reset/done/",
        PasswordResetDone.as_view(),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    category = models.CharField(max_length=50)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.category


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_("author")
    )
    title = models.CharField(max_length=200)
    text = models.TextField()
    category = models.ForeignKey(
        Category, on_delete=models.RESTRICT, null=True, blank=True
    )
    related_posts = models.ManyToManyField(
        to="self",
        symmetrical=False,
        blank=True,
        through="RelatedPost",
    )
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")


class RelatedPost(models.Model):
    main_post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="posts_related"
    )
    related_post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="posts_main"
    )

    def __str__(self):
        return f"Main: {self.main_post.title} - Related: {self.related_post.title}"

    class Meta:
        constraints = [
            models.UniqueConstraint(
                "main_post", "related_post", name="unique_mainpost_relatedpost"
            )
        ]
        verbose_name = _("Related Post")
        verbose_name_plural = _("Related Posts")


class PostRecord(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    modified_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.post} - {self.user}"

    class Meta:
        verbose_name = _("Post Record")
        verbose_name_plural = _("Post Records")


class Comment(MPTTModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=False)
    parent = TreeForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="children"
    )

    class MPTTMeta:
        order_insertion_by = ["created_date"]
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")

    def __str__(self):
        return "Comment on {} by {}".format(self.post, self.author)

blog/forms.py
from django import forms
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Submit, Row, Column, Field, Button

from .models import Post, Comment


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)

        # If you pass FormHelper constructor a form instance
        # It builds a default layout with all its fields
        self.helper = FormHelper(self)

        # You can dynamically adjust your layout
        self.helper.layout = Layout(
            Row(Column(Field("title", autofocus=True))),
            Row(Column("text")),
            Row(Column("category")),
            Submit("submit", "Save", css_class="btn btn-secondary btn-lg w-100"),
        )

    class Meta:
        model = Post
        fields = ("title", "text", "category")


class CommentForm(forms.ModelForm):
    body = forms.CharField(
        label="",
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Comment here !",
                "rows": 3,
                "cols": 50,
            }
        ),
    )

    class Meta:
        model = Comment
        fields = ["body"]

blog/views.py
from typing import Any
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models.query import QuerySet
from django.urls import reverse
from django.utils import timezone, translation
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from extra_views import (
    ModelFormSetView,
    InlineFormSetFactory,
    CreateWithInlinesView,
    UpdateWithInlinesView,
)
from django.core.exceptions import ValidationError
from django.forms import BaseModelFormSet

from .filters import PostFilter
from .forms import PostForm, CommentForm
from .models import Post, PostRecord, Comment, Category


class FilteredListView(ListView):
    filterset_class = None

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filterset"] = self.filterset
        return context


class PostListView(LoginRequiredMixin, FilteredListView):
    model = Post
    paginate_by = 10
    filterset_class = PostFilter

    def get_queryset(self) -> QuerySet[Post]:
        queryset = super().get_queryset()
        queryset = (
            queryset.filter(published_date__lte=timezone.now())
            .order_by("-published_date")
            .select_related("author", "category")
        )
        print(translation)
        return queryset


# Formsets
class PostBaseFormSet(BaseModelFormSet):

    def clean(self):
        if any(self.errors):
            return
        for form in self.forms:
            author = form.cleaned_data.get("author")
            print(author, self.kwargs["user"])
            if author != self.kwargs["user"]:
                raise ValidationError("The users must be the same")


class PostFormSetview(ModelFormSetView):
    model = Post
    fields = ("title", "category", "text")
    template_name = "blog/post_formset.html"
    factory_kwargs = {"extra": 0}
    formset_class = PostBaseFormSet

    # def get_formset_kwargs(self):
    #     kwargs = super(PostFormSetview, self).get_formset_kwargs()
    #     kwargs["user"] = self.request.user
    #     return kwargs

    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user)

    def get_success_url(self):
        return reverse("blog:post_list")


# Ex 2
class PostInline(InlineFormSetFactory):
    model = Post
    fields = ("title", "text")
    factory_kwargs = {"extra": 0, "can_order": False, "can_delete": False}


class EditCategoryPosts(UpdateWithInlinesView):
    model = Category
    inlines = [PostInline]
    template_name = "blog/category_formset.html"
    fields = ("category",)

    def get_success_url(self):
        return reverse("blog:post_list")


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["related_posts"] = self.object.posts_related.all()
        context["comment_form"] = CommentForm
        context["comments"] = self.object.comments.all().select_related("author")
        return context


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.published_date = timezone.now()
        result = super().form_valid(form)
        return result

    def get_success_url(self) -> str:
        return reverse("blog:post_detail", kwargs={"pk": self.object.pk})


class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.published_date = timezone.now()
        result = super().form_valid(form)
        # We save a new register after modifying the post
        register = PostRecord()
        register.post = self.object
        register.user = self.object.author
        register.save()
        return result

    def get_success_url(self) -> str:
        return reverse("blog:post_detail", kwargs={"pk": self.object.pk})


class AuthorDetailView(DetailView):
    model = User
    template_name = "blog/author_detail.html"
    context_object_name = "author"
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["author_posts"] = self.object.post_set.all()
        return context


class CategoryListView(ListView):
    model = Post
    template_name = "blog/category_detail.html"
    context_object_name = "posts_by_category"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        print(self.kwargs)
        category = Category.objects.get(category=self.kwargs["category"])
        queryset = Post.objects.filter(category=category)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.kwargs["category"]
        return context


class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.post = Post.objects.get(pk=self.kwargs["pk"])
        form.instance.author = self.request.user
        form.instance.created_date = timezone.now()
        if "parent" in self.kwargs:
            form.instance.parent = Comment.objects.get(pk=self.kwargs["parent"])
        result = super().form_valid(form)
        return result

    def get_success_url(self) -> str:
        return reverse("blog:post_detail", kwargs={"pk": self.kwargs["pk"]})

blog/templates/blog/author_detail.html
{% extends "blog/base.html" %}
{% load i18n %}
{% block content %}
  <div class="container">
    <h2>{% translate "Author details" %}</h2>
    <p>{% translate "Author:" %} {{ author }}</p>
    <p>{% translate "Email:" %} {{ author.email }}</p>
  </div>
  <h3 class="text-center mt-4 mb-2">{% translate "Your Posts" %}</h3>
  <div class="container">
    <div class="row">
      {% for post in author_posts %}
        <div class="col-sm-6 mb-2">
          <div class="col-12 border border-2 border-secondary rounded p-3 h-100 bg-light text-dark">
            <h5 class="font-weight-bold">{{ post }}</h5>
            <p class="mb-0">{% translate "Title:" %} {{ post.title }}</p>
            <p>{% translate "Published Date:" %} {{ post.published_date }}</p>
          </div>
        </div>
      {% empty %}
        <p class="alert alert-info">{% translate "This author hasn't published any posts yet." %}</p>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="foo" />
    <meta name="keywords" content="foo,bar" />
    <title>{% translate "Patryk's blog" %}</title>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" />
    <link rel="stylesheet" href="{% static 'css/blog.css' %}" />
  </head>
  <body>
    <header class="page-header mb-4 ">
      <nav class="navbar navbar-expand-lg navbar-light container d-flex justify-content-between">
        <h1 class="mb-0 ">
          <a class="blog-title align-middle" href="{% url 'blog:post_list' %}">{% translate "Patryk's blog" %}</a>
        </h1>
        <div class="d-flex ">
          {% if user.is_authenticated %}
            <div class="dropdown mr-4">
              <button class="btn btn-secondary border border-light text-white dropdown-toggle"
                      type="button"
                      id="dropdownMenu2"
                      data-toggle="dropdown"
                      aria-haspopup="true"
                      aria-expanded="false">{{ user.username }}</button>
              <div class="dropdown-menu dropdown-menu-right"
                   aria-labelledby="dropdownMenu2">
                <div class="d-flex justify-content-center">
                  <a href="{% url 'blog:post_new' %}" class="pt-2">{% include "./icons/file-earmark-plus.svg" %}</a>
                </div>
                <div class="dropdown-divider w-100 "></div>
                <form method="post"
                      class="d-flex justify-content-center"
                      action="{% url 'users:logout' %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-light shadow-none w-75">Logout</button>
                </form>
              </div>
            </div>
          {% endif %}
          <form action="{% url 'set_language' %}" method="post" class="d-flex">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}">
            <select class="form-control mr-1" name="language">
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
                <option value="{{ language.code }}"
                        {% if language.code == LANGUAGE_CODE %}selected{% endif %}>{{ language.code|upper }}</option>
              {% endfor %}
            </select>
            <input type="submit" class="btn btn-light " value="Go">
          </form>
        </div>
      </nav>
    </header>
    <main class="container">
      <div class="row">
        <div class="col">
          {% block content %}
          {% endblock content %}
        </div>
      </div>
    </main>
    <footer class="bg-body-tertiary text-center text-lg-start mt-3">
      <!-- Copyright -->
      {# djlint:off H021#}
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05)">
        © 2024 Copyright:
        <a class="text-body" href="#">Patryk Pyczko</a>
      </div>
      <!-- Copyright -->
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/category_detail.html
{# djlint:off H023 #}
{% extends "blog/base.html" %}
{% load i18n %}
{% block content %}
  <div class="container">
    <h2 class="text-center mb-3">
      {% blocktranslate with category=category %}
      Posts from the {{ category }} category.
      {% endblocktranslate %}
    </h2>
    <div class="row">
      {% for post in posts_by_category %}
        <div class="col-sm-6 mb-2">
          <div class="col-12 border border-2 border-secondary rounded p-3 h-100 bg-light text-dark">
            <h5>{{ post }}</h5>
            <p class="mb-0">{% translate "Title:" %} {{ post.title }}</p>
            <p>{% translate "Published Date:" %} {{ post.published_date }}</p>
          </div>
        </div>
      {% empty %}
        <p class="alert alert-info w-100 text-center">
          {% blocktranslate with category=category %}
          No existing posts for the {{ category }} category.
          {% endblocktranslate %}
        </p>
      {% endfor %}
    </div>
  </div>
  <div class="container mt-1 mb-3">
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
  </div>
{% endblock content %}

blog/templates/blog/category_formset.html
{# djlint:off H023 #}
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <hr>
    {% for formset in inlines %}{{ formset|crispy }}{% endfor %}
    <input type="submit" value="Submit" />
  </form>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load mptt_tags %}
{% load humanize %}
{% load blog_extras %}
{% load i18n %}
{% block content %}
  <article class="post">
    <aside class="actions">
      {% if user.is_authenticated %}
        <a class="btn btn-secondary"
           href="{% url 'blog:post_edit' pk=post.pk %}">{% include "./icons/pencil-fill.svg" %}</a>
      {% endif %}
    </aside>
    {% if post.published_date %}
      <time class="date mr-3">
        {{ post.published_date|naturaltime }}
      </time>
    {% endif %}
    <h2>{{ post.title }}</h2>
    <p class="text-muted mb-2 category-link">
      <a href="{% url 'blog:category_detail' category=post.category %}">{{ post.category }}</a>
    </p>
    <p>{{ post.text|linebreaksbr }}</p>
    <p class="text-muted">
      {% translate "Author:" %} <a href="{% url 'blog:author_detail' pk=post.author.pk %}">{{ user.first_name|format_author_name:user.last_name }}</a>
    </p>
  </article>
  {% if related_posts %}
    <h3>{% translate "Related Posts" %}</h3>
    <hr>
    {% for rpost in related_posts %}
      <a href="{% url "blog:post_detail" pk=rpost.related_post.pk %}">{{ rpost.related_post }}</a>
      <hr>
    {% endfor %}
  {% endif %}
  <div class="d-flex mt-4">
    <h3 class="mr-3">{% translate "Comments" %}</h3>
    {% if user.is_authenticated %}
      <p>
        <button class="btn btn-secondary btn-sm"
                type="button"
                data-toggle="collapse"
                data-target="#collapseForm"
                aria-expanded="false"
                aria-controls="collapseForm">+</button>
      </p>
    {% endif %}
  </div>
  <div id="collapseForm" class="collapse">
    <form method="post"
          action="{% url 'blog:comment_new' pk=post.pk %}"
          class="p-3 bg-light rounded">
      {% csrf_token %}
      {{ comment_form|crispy }}
      <input type="submit"
             value="{% translate "SEND!" %}"
             class="btn btn-secondary w-100" />
    </form>
  </div>
  <hr>
  <div class="root">
    {% recursetree comments %}
    <div>
      <div class="border border-dark rounded p-3 bg-light mb-2">
        <p class="text-muted mb-2">{{ node.author }} - {{ node.created_date }}</p>
        <p class="mb-0">{{ node.body }}</p>
        {% if user.is_authenticated %}
          <p class="d-flex justify-content-end mb-0">
            <button class="btn btn-secondary btn-sm"
                    type="button"
                    data-toggle="collapse"
                    data-target="#collapseForm{{ node.pk }}"
                    aria-expanded="false"
                    aria-controls="collapseForm{{ node.pk }}">Reply</button>
          </p>
        {% endif %}
      </div>
      <div id="collapseForm{{ node.pk }}" class="collapse">
        <form method="post"
              action="{% url 'blog:comment_new_child' pk=post.pk parent=node.pk %}"
              class="p-3 bg-light rounded">
          {% csrf_token %}
          {{ comment_form|crispy }}
          <input type="submit"
                 value="{% translate "SEND!" %}"
                 class="btn btn-secondary w-100" />
        </form>
      </div>
      {% if not node.is_leaf_node %}
        <ul class="children">
          {{ children }}
        </ul>
      {% endif %}
    </div>
  {% endrecursetree %}
  {% if not comments %}
    <p class="alert alert-info">{% translate "This post doesn't have any comments yet." %}</p>
  {% endif %}
  <div class="mt-4">
    <h3>Latest posts from the {{ post.category }} category</h3>
    <hr>
    {% for post in post.category|last_posts %}
      <a href="{% url "blog:post_detail" pk=post.pk %}">{{ post.title }}</a>
      <hr>
    {% endfor %}
  </div>
</div>
{% endblock content %}

blog/templates/blog/post_edit.html
{% extends "blog/base.html" %}
{% block content %}
  <h2>New post</h2>
  <form method="post" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-secondary">Save</button>
  </form>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
  <h2>{% translate "New post" %}</h2>
  {% crispy form %}
{% endblock content %}

blog/templates/blog/post_formset.html
{# djlint:off H023 #}
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ formset|crispy }}
    <input type="submit" value="Submit" />
  </form>
  {% comment %} {% for form in formset %}
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit" />
      {% for dict in form.errors %}
        {% for error in dict.values %}{{ error }}{% endfor %}
      {% endfor %}
    </form>
  {% endfor %} {% endcomment %}
{% endblock content %}

blog/templates/blog/post_list.html
{# djlint:off H023 #}
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load blog_extras %}
{% load i18n %}
{% block content %}
  <div class="dropdown mb-4">
    <button class="btn btn-secondary dropdown-toggle w-100"
            type="button"
            id="dropdownMenuButton"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false">{% translate "Filter Posts" %}</button>
    <div class="dropdown-menu w-100 m-0 p-0"
         aria-labelledby="dropdownMenuButton">
      <form method="get" class="p-3 bg-light">
        {{ filterset.form|crispy }}
        <input type="submit"
               value="{% translate "SEND!" %}"
               class="btn btn-secondary w-100" />
      </form>
    </div>
  </div>
  <div>
    {% for post in object_list %}
      <article class="post">
        <time class="date">
          {{ post.published_date|naturaltime }}
        </time>
        <h2 class="mb-1">
          <a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
        </h2>
        <p class="text-muted mb-2 category-link">
          <a href="{% url 'blog:category_detail' category=post.category %}">{{ post.category }}</a>
        </p>
        <p>{{ post.text|linebreaksbr }}</p>
        <p class="text-muted">
          {% translate "Author:" %} <a href="{% url 'blog:author_detail' pk=post.author.pk %}">{{ post.author.first_name|format_author_name:post.author.last_name }}</a>
        </p>
      </article>
    {% empty %}
      <p class="alert alert-info">{% translate "No posts found with the matching criteria." %}</p>
    {% endfor %}
  </div>
  <div class="pagination mb-4">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; {% translate "first" %}</a>
        <a href="?page={{ page_obj.previous_page_number }}">{% translate "previous" %}</a>
      {% endif %}
      <span class="current">{% translate "Page" %} {{ page_obj.number }} {% translate "of" %} {{ page_obj.paginator.num_pages }}.</span>
      {% if page_obj.has_next %}
        <a href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">{% translate "next" %}</a>
        <a href="?{{ request.GET.urlencode }}&page={{ page_obj.paginator.num_pages }}">{% translate "last" %} &raquo;</a>
      {% endif %}
    </span>
  </div>
{% endblock content %}