blog/urls.py
from django.urls import path
from . import views
from .models import Post
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    AuthorDetailView,
    CategoryListView,
    CommentCreateView,
    PostFormSetview,
    EditCategoryPosts,
)
from users.views import LoginUserView

app_name = "blog"

urlpatterns = [
    path("", PostListView.as_view(), name="post_list"),
    path("post/new/", PostCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("comment/<int:pk>/", CommentCreateView.as_view(), name="comment_new"),
    path(
        "comment/<int:pk>/parent/<int:parent>/",
        CommentCreateView.as_view(),
        name="comment_new_child",
    ),
    path(
        "post/category/<str:category>/",
        CategoryListView.as_view(),
        name="category_detail",
    ),
    path("post/<int:pk>/edit/", PostUpdateView.as_view(), name="post_edit"),
    path("author/<int:pk>/", AuthorDetailView.as_view(), name="author_detail"),
    # Form sets
    path("post/formset/", PostFormSetview.as_view(), name="post-formset"),
    path(
        "category/formset/<int:pk>/",
        EditCategoryPosts.as_view(),
        name="category-formset",
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
]

users/urls.py
from django.urls import path

from .views import (
    LoginUserView,
    LogoutUser,
    SignUpUser,
    PasswordReset,
    PasswordResetDone,
)
from django.contrib.auth.views import (
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy
from blog.urls import PostListView

app_name = "users"

urlpatterns = [
    path("accounts/login/", LoginUserView.as_view(), name="login"),
    path("accounts/logout", LogoutUser.as_view(), name="logout"),
    path("accounts/signup/", SignUpUser.as_view(), name="signup"),
    path("accounts/password_reset/", PasswordReset.as_view(), name="password_reset"),
    path(
        "accounts/password_reset/done/",
        PasswordResetDone.as_view(),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Column, Field, Row, Submit
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        # If you pass FormHelper constructor a form instance
        # It builds a default layout with all its fields
        self.helper = FormHelper(self)

        # You can dynamically adjust your layout
        self.helper.layout = Layout(
            Row(Column(Field("username", autofocus=True))),
            Row(Column("password")),
            Submit("submit", "Submit", css_class="btn btn-secondary btn-lg w-100"),
        )


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text="Optional.")
    last_name = forms.CharField(max_length=30, required=False, help_text="Optional.")
    email = forms.EmailField(
        max_length=254, help_text="Required. Inform a valid email address."
    )

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        # If you pass FormHelper constructor a form instance
        # It builds a default layout with all its fields
        self.helper = FormHelper(self)

        # You can dynamically adjust your layout
        self.helper.layout = Layout(
            Row(Column(Field("username", autofocus=True))),
            Row(Column("first_name")),
            Row(Column("last_name")),
            Row(Column("email")),
            Row(Column("password1")),
            Row(Column("password2")),
            Submit("submit", "Submit", css_class="btn btn-secondary btn-lg w-100"),
        )

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

users/views.py
from django.contrib.auth import login
from django.contrib.auth import views as auth_views
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import LoginForm, SignUpForm


class LoginUserView(auth_views.LoginView):
    template_name = "users/login.html"
    authentication_form = LoginForm
    next_page = "blog:post_list"
    redirect_authenticated_user = True


class LogoutUser(auth_views.LogoutView):
    template_name = "users/logout.html"


class SignUpUser(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy("blog:post_list")
    template_name = "users/signup.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("blog:post_list")
        return super().get(request, *args, **kwargs)

    # Automatic login after signup
    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        return response


class PasswordReset(auth_views.PasswordResetView):
    template_name = "users/password_reset_form.html"
    success_url = reverse_lazy("users:password_reset_done")


class PasswordResetDone(auth_views.PasswordResetDoneView):
    template_name = "users/password_reset_done.html"

users/templates/users/login.html
{# djlint:off H030, H031 #}
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
  <h2 class="text-center mb-3">{% translate "Welcome To Our Blog" %}</h2>
  <div class="login-form container border border-secondary rounded p-3">{% crispy form %}</div>
  <p class="alert alert-info text-center mt-4">
    {% translate "Haven't signed up yet?" %} <a href="{% url "users:signup" %}">{% translate "Click here!" %}</a>
  </p>
  <p class="text-muted">
    {% translate "Forgot your password? Reset it" %} <a href="{% url "users:password_reset" %}">{% translate "here" %}</a>
  </p>
{% endblock content %}

users/templates/users/logout.html
{% extends "blog/base.html" %}
{% load i18n %}
{% block content %}
  <h2 class="alert alert-info">
    {% translate "You have logged out successfully." %}
    <br>
    {% translate "To login again," %} <a href="{% url 'users:login' %}">{% translate "click here" %}</a>
  </h2>
{% endblock content %}

users/templates/users/password_reset_complete.html
{# djlint: off #}
{% extends 'blog/base.html' %}
{% load i18n %}
{% block title %}{% translate "Password reset complete" %}{% endblock %}

{% block content %}
<h2 class="mb-3">{% translate "Password reset complete" %}</h2>
<p>{% translate "Your new password has been set. You can log in now on the" %} <a href=" {% url 'users:login' %}">{% translate "log in page" %}</a>.</p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{# djlint: off #}
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}

{% if validlink %}

<h2 class="mb-3">{% translate "Set a new password!" %}</h2>
<form method="POST">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" class="btn btn-secondary" value="{% translate "Change my password" %}">
</form>

{% else %}

<p>{% translate "The password reset link was invalid, possibly because it has already been used. Please request a new password reset." %}</p>

{% endif %}
{% endblock content %}

users/templates/users/password_reset_done.html
{# djlint: off #}
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
  <h2>{% translate "Check your inbox." %}</h2>
  <p> {% translate "We've emailed you instructions for setting your password. You should receive the email shortly!" %}</p>
{% endblock content %}

users/templates/users/password_reset_form.html
{# djlint: off #}
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
  <h2 class="mb-2">{% translate "Forgot your password?" %}</h2>
  <p>{% translate "Enter your email address below, and we'll email instructions for setting a new one." %}</p>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy}}
    <input type="submit" class="btn btn-secondary" value="{% translate "Send me instructions!" %}">
  </form>
{% endblock content %}

users/templates/users/signup.html
{# djlint:off H030, H031 #}
{% extends "blog/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
  <h2 class="text-center mb-3">{% translate "Sign Up To Our Blog" %}</h2>
  <div class="login-form container border border-secondary rounded p-3 mb-4">{% crispy form %}</div>
{% endblock content %}